### ISSUE TITLE
Can this poc work if we run "./process.py" directly without "sudo"?

### ISSUE THREAD

**Issue by linlanfeng** [HexHive/SMoTherSpectre#2]
Since the port covert channel does not rely on "sudo" in theory, we tried to set "use_pmc" in the process.py to be 0 and execute "./process.py" without "sudo".  It turns out that the accuracy of the poc is 54% without "sudo", but 98% with "sudo". Does this poc work without "sudo" or is there any code we need to change?

**Comment by atrib** [comment]
**Tl;dr:** 
The poc code works without superuser permissions. 
As a sanity check:
- check if your threshold is the correct
- try changing the number of samples have.

**Longer reply**

I attempted the same change as you. Specifically, The change is:
```
@@ -13,8 +13,8 @@ def build(nsample, threshold, use_pmc = 1):
 def run_expt():
     oss.call(['./orchestrator'])
 
-def get_accuracy(nsample = 2, threshold = 94):
-    build(nsample, threshold)
+def get_accuracy(nsample = 2, threshold = 88):
+    build(nsample, threshold, use_pmc = 0)
```
The threshold change is due to the particular machine I'm running on. 
My output to running `process.py` without sudo shows a definite signal.

```
Accuracy for 1 samples per expt is  0.53
Accuracy for 2 samples per expt is  0.594
Accuracy for 3 samples per expt is  0.631
Accuracy for 4 samples per expt is  0.636
Accuracy for 5 samples per expt is  0.612
Accuracy for 6 samples per expt is  0.512
Accuracy for 7 samples per expt is  0.738
Accuracy for 8 samples per expt is  0.65
Accuracy for 9 samples per expt is  0.761
```
